data:
  db: megaagemerge
  db_test: datasetmerge_test
  db_train: datasetmerge_train

model:
  model_name: EfficientNetB3
  img_size: 256

train:
  optimizer_name: adam
  lr: 0.001
  epochs: 30
  batch_size: 32

wandb:
  project: null
