data:
  db: megaage
  db_test: megaage_asian_test
  db_train: megaage_asian_train

model:
  model_name: EfficientNetB3
  img_size: 224

train:
  optimizer_name: adam
  lr: 0.001
  epochs: 3000
  batch_size: 64

wandb:
  project: null
